# Generated by Django 2.0.3 on 2018-03-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver_detail',
            name='vehicle_location_altitute',
            field=models.FloatField(max_length=40),
        ),
        migrations.AlterField(
            model_name='driver_detail',
            name='vehicle_location_latitute',
            field=models.FloatField(max_length=40),
        ),
    ]
