# Generated by Django 2.0.3 on 2018-03-17 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_auto_20180316_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver_detail',
            name='vehicle_location_altitute',
        ),
        migrations.RemoveField(
            model_name='driver_detail',
            name='vehicle_location_latitute',
        ),
        migrations.AddField(
            model_name='driver_detail',
            name='current_vehicle_location',
            field=models.CharField(default='Jabalpur', max_length=60),
        ),
        migrations.AddField(
            model_name='driver_detail',
            name='distance_covered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driver_detail',
            name='last_stoppage',
            field=models.CharField(default='delhi', max_length=60),
        ),
    ]
