# Generated by Django 2.0.3 on 2018-03-17 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_auto_20180317_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver_detail',
            name='vehicle_status',
            field=models.IntegerField(choices=[('running', 1), ('scheduled', 0), ('stop', -1)]),
        ),
    ]
