# Generated by Django 2.0.3 on 2018-03-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0006_auto_20180317_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver_detail',
            name='last_update',
            field=models.IntegerField(default=40),
        ),
    ]
